name: Publish Dev Container Features & Templates

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish features
        uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: devcontainer-features/src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish templates
        uses: devcontainers/action@v1
        with:
          publish-templates: true
          base-path-to-templates: devcontainer-templates/src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
